version: "3.9"
services:
  db:
    image: world_db_mysql_8.0
    # コンテナ名を設定
    container_name: "world_db"
    volumes:
      # データ永続化
      - ./data:/var/lib/mysql
    ports:
      - "13306:3306"
    # ヘルスチェック
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  api:
    image: world_api_node18.14-slim
    # コンテナ名を設定
    container_name: "world_api"
    environment:
      DB_HOST: world_db
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: rootpass
      DB_DATABASE: world
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3001"
  # ui:
  #   image: world_ui_node18.14-slim
  #   # コンテナ名を設定
  #   container_name: "world_ui"
  #   depends_on:
  #     - api
  #   ports:
  #     - "3300:3000"
